name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.yarn/cache 
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install dependencies
        run: yarn install

      - name: Save node_modules as artifact
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: node_modules

  lint_and_format:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dependencies artifact
        uses: actions/download-artifact@v3
        with:
          name: node_modules

      - name: Run Prettier
        run: yarn prettier --check .

      - name: Run ESLint
        run: yarn eslint . --max-warnings=0

  tsc_check:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dependencies artifact
        uses: actions/download-artifact@v3
        with:
          name: node_modules

      - name: Run TypeScript Compilation (tsc)
        run: npx tsc --noEmit

  audit:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Download dependencies artifact
        uses: actions/download-artifact@v3
        with:
          name: node_modules

      - name: Run audit
        run: yarn audit --production

  outdated:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Download dependencies artifact
        uses: actions/download-artifact@v3
        with:
          name: node_modules

      - name: Check outdated dependencies
        run: yarn check-outdated || echo "No outdated dependencies found"
        continue-on-error: true

  test_coverage:
    runs-on: ubuntu-latest
    needs: [lint_and_format, tsc_check]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Download dependencies artifact
        uses: actions/download-artifact@v3
        with:
          name: node_modules

      - name: Run tests with coverage
        run: yarn test
